# Generated by Django 4.2.4 on 2023-08-30 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_answer_1_author_answer_2_author_question_1_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer_1',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answer_2',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_1',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_2',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
