# Generated by Django 4.2.4 on 2023-08-30 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_answer_1_modify_date_answer_2_modify_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer_1',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer_1',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='answer_2',
            name='author',
        ),
        migrations.RemoveField(
            model_name='answer_2',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question_1',
            name='modify_date',
        ),
        migrations.RemoveField(
            model_name='question_2',
            name='modify_date',
        ),
    ]
