# Generated by Django 4.2.4 on 2023-08-30 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_remove_answer_1_author_remove_answer_1_modify_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question_1',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question_2',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
