# Generated by Django 4.2.4 on 2023-08-29 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawledData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField(max_length=300)),
                ('img_link', models.URLField(max_length=300)),
                ('text_file', models.FileField(blank=True, null=True, upload_to='text_files/')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='image_file/')),
            ],
        ),
    ]
