# Generated by Django 4.2.4 on 2023-08-29 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='checklist',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
