# Generated by Django 4.2.4 on 2023-08-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_user_history_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_history',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
